name: Beta 1.17.1 Report
description: Report a bug in the beta 1.17.1
labels: [beta, 1.17.1, checking]
body:
  - type: markdown
    attributes:
      value: |
        Welcome to the place to report issues for the beta 1.17.1. If you have only questions, please consider to ask them on the [Official Page](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone)
        Make to sure to provide any information that can help in the resolution of the issue.
        The language used to fill the information is english, but can be in french as long as you're really french native (no google translation).
        Also make sure you're using the latest beta and if this is not a known issue:
        - [nothing actually]
  
  - type: markdown
    attributes:
      value: "## Versions"
      
  - type: input
    id: forge-version
    attributes:
      label: Forge Version
    validations:
      required: true
      
  - type: input
    id: tombstone-version
    attributes:
      label: Corail Tombstone Version
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: "## Issue Description"
             
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen? What are the steps to reproduce it
      placeholder: Try to provide the maximum of details!
    validations:
      required: true

  - type: input
    id: log-link
    attributes:
      label: Log Link
      description: paste a link for logs in case of crash or if relevant in the resolution of the issue
      placeholder: pastebin link

  - type: dropdown
    id: gametype
    attributes:
      label: Gametype
      multiple: true
      options:
        - Singleplayer
        - Dedicated Server
    validations:
      required: true
      
  - type: dropdown
    id: tombstone-only
    attributes:
      label: Happen with only Corail Tombstone
      description: you have been able to make this issue happening with only Corail Tombstone. If you don't make this test, your issue will be directly closed without any answer
      options:
        - No
        - Yes
    validations:
      required: true

  - type: input
    id: relevant-mods
    attributes:
      label: Relevant others mods
      description: a short list of mods (max 5) to make the issue happening or just "Corail Tombstone" if it's reproducible with only this mod
      placeholder: mods to make the issue happening
    validations:
      required: true 
          