name: Bug Report
description: Report an issue
title: "Bug: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Welcome to the place to report issues. If you have only questions, please consider to ask them on the [Official Page](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone)**
        Make to sure to provide any information that could help in the resolution of the issue.
        The language used to fill the information is english, but can be in french as long as you're really french native (no google translation).
  
  - type: markdown
    attributes:
      value: "## Versions"
      
  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      multiple: true
      options:
        - 1.16.5
        - 1.12.2
    validations:
      required: true
      
  - type: input
    id: forge-version
    attributes:
      label: Forge Version
    validations:
      required: true
      
  - type: input
    id: tombstone-version
    attributes:
      label: Corail Tombstone Version
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: "## Issue Description"
             
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen? What are the steps to reproduce it
      placeholder: Try to provide the maximum of details!
      value: "A bug happened!"
    validations:
      required: true

  - type: input
    id: log-link
    attributes:
      label: Log Link
      description: paste a link for logs in case of crash or if relevant in the resolution of the issue

  - type: dropdown
    id: gametype
    attributes:
      label: Gametype
      multiple: true
      options:
        - Singleplayer
        - Dedicated Server
    validations:
      required: true
      
  - type: checkboxes
    id: tombstone-only
    attributes:
      label: Tested with only Corail Tombstone
      description: you have been able to reproduce the issue with only Corail Tombstone
      options:
        - label: "Yes"

  - type: input
    id: relevant-mods
    attributes:
      label: Relevant others mods to make the issue happening
    validations:
      required: false    
          