blank_issues_enabled: false
contact_links:
  - name: Corail Tombstone Official Page
    url: https://www.curseforge.com/minecraft/mc-mods/corail-tombstone/
    about: Please use this link for questions or suggestions.